### ISSUE TITLE
JSON decode error when calling sync_nft_contract

### ISSUE THREAD

**Issue by pvanderlinden** [MoralisWeb3/Moralis-Python-SDK#35]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-Python-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-Python-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-Python-SDK/releases), and my server is updated to the latest version.

### Issue Description

Exception:
```
Traceback (most recent call last):
  File "/home/paul/repos/early-exploration/contract-names/source_moralis.py", line 25, in <module>
    evm_api.nft.sync_nft_contract(
  File "/home/paul/.cache/pypoetry/virtualenvs/contract-names-AXv8L-X6-py3.10/lib/python3.10/site-packages/moralis/evm_api/nft/sync_nft_contract.py", line 25, in sync_nft_contract
    return json.loads(api_response.response.data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Steps + code to reproduce

```
from moralis import evm_api
evm_api.nft.sync_nft_contract(
          api_key="...",
          params={"chain": "eth", "address": "0x046dac4d647e1d2b026ec54be819fe2ee59de8fd"},
)
```

### Actual Outcome

The above exception

### Expected Outcome

An "ok" from the api. The api instead returns an empty string, but the SDK doesn't accept that

### Environment

Server

- Moralis server version: latest (not self hosted)

Client

- Moralis SDK version: 0.1.36
- Operating system: Linux
- Browser: None

**Comment by b4rtaz** [comment]
Hi @pvanderlinden! We are working on a fix now...

**Comment by b4rtaz** [comment]
Could you check the `0.1.37` version?
